### PR TITLE
Removed copying Packages folder and replaced it with symlinking

### PR DESCRIPTION
**Pull request by brogan89**
Fixes Bug #57

### CODE REVIEW

**Comment by brogan89** [comment]
Satisfies feature request #58

**Comment by mikz** [comment]
This was revered in https://github.com/VeriorPies/ParrelSync/commit/f3a9c52950bb55c4830c9cd474d4b804a174245e because of https://github.com/VeriorPies/ParrelSync/issues/23

**Comment by mikz** [comment]
Well, it was not really problem about updating packages. But Unity showed a window "Resolving packages" for a few seconds whenever you changed focus between windows or when some script was changed. That was quite annoying.

**Comment by mikz** [comment]
I tried it with 2021.1.28 and I can't reproduce #23 but entirely new issue appears.
If I open two Rider windows it starts consuming 100% CPU and overriding each other's packages. 

I think this behaviour should be configurable as depending on the workflow it might cause issues.

**Comment by 314pies** [comment]
Hi folks!

Thanks for bringing this up; Gonna take a deeper look later.

**Comment by mikz** [comment]
Maybe just a button in menu to force the sync would be ok too. You don't change packages very often.

**Comment by Fangjun-Zhou** [comment]
> Maybe just a button in menu to force the sync would be ok too. You don't change packages very often.

I've added a preference checkbox to let users decide whether to sync Package, I'm not sure if that helps. Latter I will try to add another feature to force sync the Package folder. I still think this is important. At least for me, I changed package directory very often.

**Comment by kamyker** [comment]
> I tried it with 2021.1.28 and I can't reproduce #23 but entirely new issue appears. If I open two Rider windows it starts consuming 100% CPU and overriding each other's packages.
> 
> I think this behaviour should be configurable as depending on the workflow it might cause issues.

No issues for me in Unity 2023, imo Package symlinking should be on by default.

**Comment by RunninglVlan** [comment]
README is also confusing - it tells that Packages are symlinked, when in fact they're just copied

**Pull request closed without merging**
