### PR TITLE
macOS support

### PR DESCRIPTION
**Pull request by dudareviv**

### CODE REVIEW

**Comment by 314pies** [comment]
Cool, will take a deeper look in a few days!

**Comment by 314pies** [comment]
I've check out your commits.
The sym links and project deletion work great.
However there seems to have a little issue with the clone project running status in the clone manager windows.
I think this is due to the different file locking mechanic between Unity win and mac editor.
I should able to fix that soon.

**Comment by dudareviv** [comment]
It will be great.

**Comment by 314pies** [comment]
I've merge your PR to the develop branch. 
A beta which support Mac will be released later, if no critical issues was found, it will then be released as a stable version in few weeks.
Thanks for your awesome contribution 🍡 !

**Pull request merged**
