### PR TITLE
Added options to synch package directory and choose clone location.

### LINKED ISSUE #80: [BUG] Git submodule not synchronized.
**Describe the bug**
When I use the git submodule inside the Package directory, changes are not synchronized through projects.

**To Reproduce**
1. Use git submodule to add a submodule inside Package dir.
2. Make some changes to the submodule in the parent project.
3. The package in the child project will not change.

**Expected behavior**
Ideally, all the changes should be synchronized. I'm not sure it is because there's some limitation with symbol links for submodules.

**Screenshots/Video**
None

**Enviroment (please complete the following information):**
 - Unity Editor Version: Windows 2020.3.25f1
 - ParrelSync Version: 1.5.0
 - OS Version: Windows 10 21H2

**Additional context**
None

### PR DESCRIPTION
**Pull request by fangjunzhou**
Added symbolic link option for Package directory.
Closed #80

### CODE REVIEW

**Comment by Fangjun-Zhou** [comment]
I found that sometimes people need to create symbolic links for the Package directory. I mentioned that in #80. I then found that by default ParrelSync only copies the content in the Package directory. So I added an option for users to decide whether to create a symbolic link for the directory.

**Comment by Fangjun-Zhou** [comment]
Closed #79
Added custom clone location. Use a scriptable object settings file to keep track of all the clone project paths.
I've added a migrate method so that the old version will not lose the cloned project path record.

**Comment by 314pies** [comment]
Thanks Fangjun-Zhou!
Will take a deeper look later!

**Comment by kamyker** [comment]
Shouldn't this be default? I don't get why Packages folder would have to be copied?

I don't get any issues with symlinked folder at least in Unity 2023.

**Review by sharad-0 — APPROVED** [review]

**Comment by TEXAS-777** [comment]
@314pies 
Hi, I found that PR #81 (“Added options to sync package directory and choose clone location”) was closed without merging.
This feature seems really useful — could I ask why it was closed? Was there a specific issue or conflict?

Thanks!

**Pull request closed without merging**
